### ISSUE TITLE
Getting all episodes and season credits (appending to response)

### ISSUE THREAD

**Issue by gbdematos** [php-tmdb/api#170] opened 2018-01-10 21:15 UTC
If I try to do:
```
$repo->load($tmdbId, ['append_to_response' => ['season/1', 'season/1/credits', 'season/2'....]])
```
The appended items get lost when converting to the TV Model.

How do I retrieve this information?

Or... is there any other way to do this, without having to do X (number of seasons) times 2 (for credits) requests to the server?

**Comment by wtfzdotnet** [comment] 2018-05-03 18:36
Planning to still look at this at a later time! Could mean a significant performance enhancement if we get this working properly.

**Comment by wtfzdotnet** [comment] 2021-01-05 21:55
I've just tried to reproduce this as

```php
<?php

/**
 * This file is part of the Tmdb PHP API created by Michael Roterman.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @package Tmdb
 * @author Michael Roterman <michael@wtfz.net>
 * @copyright (c) 2013, Michael Roterman
 * @version 4.0.0
 */

require_once '../../../vendor/autoload.php';
require_once '../../apikey.php';

/** @var Tmdb\Client $client * */
$client = require_once('../../setup-client.php');
$tvShow = $client->getTvApi()->getTvshow(1396, ['season/1', 'season/1/credits']);

var_dump($tvShow);
```

However as far as documentation goes around the `append_to_response` paramters, it's only valid for methods within the same namespace, as the season calls etc. live within another namespace I believe this is not possible. Closing since this issue is ages old, if this does again need a follow-up let me know.

**Closed by wtfzdotnet** 2021-01-05 21:55 UTC
Labels: enhancement, investigate
